### ISSUE TITLE
"Нова заява" - rebuild tab "Основна інформація"

### ISSUE THREAD

**Issue by illay1994** [ifnul/ums-admission-frontend#102]
Поставити активні ChekBox
Бюджет
Контракт
Тип вступу->За даними сертифіката
Деталiзацiя вступу->За даними сертифіката

**Comment by mkozhukharenko** [comment]
fixed

**Comment by mkozhukharenko** [comment]
fixed, test please

**Comment by MPushkar** [comment]
Was tested on Build#39.
