### ISSUE TITLE
Персони: misspelling in "призвіщу" option within a "Пошук по:" drop-down list.

### ISSUE THREAD

**Issue by MPushkar** [ifnul/ums-admission-frontend#105]
<b>"Персони" tab</b>:
Misspelling in "<b>призвіщу</b>" option within a "Пошук по:" drop-down list:
![lnu_search_by](https://cloud.githubusercontent.com/assets/12950571/8548844/fadea762-24cf-11e5-8e94-eaa5679ab183.PNG)

Correct name of option is "<b>прізвищу</b>".

**Comment by mkozhukharenko** [comment]
fixed, please test

**Comment by MPushkar** [comment]
Was tested on Build#39.
