### ISSUE TITLE
Персони: An empty input form opens when user clicks "edit' button to modify data for existing Person.

### ISSUE THREAD

**Issue by MPushkar** [ifnul/ums-admission-frontend#108]
Pre-conditions:
- Any personal <b>Record1</b> should be present in system.

Steps to reproduce:
1. Login to System under Admin and go to a "Персони" tab.
2. Click ![57b5f09e-21ab-11e5-8c39-5d268842db28](https://cloud.githubusercontent.com/assets/12950571/8567934/072c9914-2572-11e5-9dee-42fa373c7b24.png) button for the <b>Record1</b>.

Actual result:
An input form is opened with <b>blank</b> values in all fields.

Expected result:
An input form should be opened with Person's data.

**Comment by mkozhukharenko** [comment]
fixed

**Comment by MPushkar** [comment]
Was tested on Build#39.
