### ISSUE TITLE
[critical] Створення персони- місце народження

### ISSUE THREAD

**Issue by illay1994** [ifnul/ums-admission-frontend#14]
коли вибираєш місце народження спочатку поясляється країна потім області а потім міста. Не дуже очевидно все у одному полі, відповідно його кожного раз треба переоберати.
Коли вибираєш адміністративну одиницю і вона є проміжна то щоб дроббокс сам випадав підсказуючи користувачу щоб він далі втбирав.

**Comment by ITsvetkoFF** [comment]
Better solution proposed in PR #31 
Illya, please review.

**Comment by MPushkar** [comment]
Igor, I assume that current enhancement had been improved within Pull #31.
Maybe we can close this item. What do you think?

**Comment by ITsvetkoFF** [comment]
yes, we can close this one
