### ISSUE TITLE
Incorrect data

### ISSUE THREAD

**Issue by Krapka** [ifnul/ums-admission-frontend#21]
Steps to reproduce
1. Open ‘ЛНУ’ project
2. Open ‘Персони’ page
3. Click ‘+Додати персону’ button
4. In field ‘Ім’я’ and ‘Прізвище’ enter ‘123’

Expected result

Field should be highlighted red as incorrect data entered (like in ‘Прізвище (англ)’ field)

Result

This field doesn`t react on incorrect data
![12](https://cloud.githubusercontent.com/assets/8030424/8129248/fff00d14-110f-11e5-8158-c46236186357.jpg)

**Comment by MPushkar** [comment]
Returned:
"По-батьковi" field should have same validation as well.

**Comment by okrasn** [comment]
fixed in pull https://github.com/ifnul/ums-admission-frontend/pull/45
