### ISSUE TITLE
Збивається дата народження

### ISSUE THREAD

**Issue by Krapka** [ifnul/ums-admission-frontend#22]
В "додавання персони", "основна інформація" дата народження відображається некоректно. Збивається після переходу на іншу вкладку
![f913e7efc735e9343915c4162aa3513e](https://cloud.githubusercontent.com/assets/8030424/8129511/8f0d2fac-1112-11e5-8c2a-2fa8f9993073.png)

**Comment by ITsvetkoFF** [comment]
fixed in Pull Request #30
