### ISSUE TITLE
Не зберігається інформація

### ISSUE THREAD

**Issue by Krapka** [ifnul/ums-admission-frontend#23]
Після заповнення всіх полів, кнопка "зберегти" неактивна. А після натискання "видалити" нічого не змінюється
Відтворення http://gyazo.com/8eee65a6cc1ab24a4ff5f384c7f583a1

**Comment by ITsvetkoFF** [comment]
It may be fixed after progressbar fix.

**Comment by ITsvetkoFF** [comment]
as I remember button should be active only after entering the addess.
