### ISSUE TITLE
Неактивне посилання

### ISSUE THREAD

**Issue by Krapka** [ifnul/ums-admission-frontend#24]
В "Додавання пропозиції" при наведені на посилання "пропозиції" з'являється текстовий курсор
![6b64c74adb3435c2086628c7f148d9e5](https://cloud.githubusercontent.com/assets/8030424/8148715/3ca86a78-12b2-11e5-95c5-a81487a4b4f6.png)

**Comment by ITsvetkoFF** [comment]
fixed in Pull Request #30
