### ISSUE TITLE
Порожнє вікно сповіщення

### ISSUE THREAD

**Issue by Krapka** [ifnul/ums-admission-frontend#26]
При пересувнні по сайту кнопками "вперед" "назад" в  деяких випадках (наприклад з меню "заяви" повернутись в "пропозиції") з'являється порожня спливаюча підказка.
![bd420b4c248198c84fc9ce33454f1a84](https://cloud.githubusercontent.com/assets/8030424/8148871/7e2fa19a-12b8-11e5-9e81-3abb31d78725.png)

**Comment by yelyzaveta-buts** [comment]
in progress

**Comment by ITsvetkoFF** [comment]
fixed in Pull Request #27
