### ISSUE TITLE
[low] Кнопка перегляду

### ISSUE THREAD

**Issue by Krapka** [ifnul/ums-admission-frontend#36]
У вступній компанії вона відсутня, а в списку персон вона є. Так і має бути?
![164ee9c77bc8167fbe48e7edac2f1d56](https://cloud.githubusercontent.com/assets/8030424/8217860/63ac88e6-1548-11e5-90ab-1ce41864d683.png)

**Comment by mkozhukharenko** [comment]
напевно немає бути.
потрібно уточнити у @illay1994 
relates to #97
