### ISSUE TITLE
[low] Проблеми при створення пропозиції

### ISSUE THREAD

**Issue by ITsvetkoFF** [ifnul/ums-admission-frontend#4]
Після занесення всієї інформації у поля і натисканні Зберегти відправляється {note: "some note"}
причому це поле не є обов`язкове

**Comment by ITsvetkoFF** [comment]
Цей issue створений Іллею перенесено мною з нашого групового репозиторію. Ілля, підкажи що по ньому треба зробити?

**Comment by illay1994** [comment]
У всіх запитах POST до back-end не має бути поля note

**Comment by okrasn** [comment]
fixed in pull https://github.com/ifnul/ums-admission-frontend/pull/38

**Comment by ITsvetkoFF** [comment]
fixed
