### ISSUE TITLE
Login page GUI issues

### ISSUE THREAD

**Issue by MPushkar** [ifnul/ums-admission-frontend#42]
Following GUI issues should be fixed on the login page:

1) Actual result: A colon character is missing after the "Будь ласка, авторизуйтеся".
Expected: "Будь ласка, авторизуйтеся:"

2) Actual result: "Ввійти" is not the best label for the button.
Expected: Either "Увійти" or "Авторизуватися" should be used instead.

![lnu_login_page](https://cloud.githubusercontent.com/assets/12950571/8241253/eb0188fa-1610-11e5-8401-9d7c536e5113.png)

**Comment by MPushkar** [comment]
Please put the colon character after the "Будь ласка, авторизуйтеся".

**Comment by okrasn** [comment]
fixed in pull https://github.com/ifnul/ums-admission-frontend/pull/45
