### ISSUE TITLE
[critical] URLs to an old server should be replaced with URLs to a new server all over Frontend

### ISSUE THREAD

**Issue by MPushkar** [ifnul/ums-admission-frontend#43]
Steps to reproduce:
1. Login to system under Admin and go to a "Пропозиції" tab.
2. Click "Створити нову вступну кампанію" and type-in any valid values into the form.
3. Click "Створити" button.

Expected result:
New record should be added.

Actual result:
New record cannot be added because the request has been sent to an old IP (104.236.29.16) instead of a new one (194.44.198.222).

PLEASE NOTE that the URLs should be fixed all over Frontend.

![lnu_old_url](https://cloud.githubusercontent.com/assets/12950571/8252687/bb71b094-1690-11e5-95f8-4eb69ec65aff.png)

**Comment by okrasn** [comment]
![43](https://cloud.githubusercontent.com/assets/1484822/8268001/880a648c-177e-11e5-9e12-2ccfd8476038.png)

Знайшов посилання на 2 різні серваки. Не видаляв, щоб не зламати, було б краще щоб людина яка більше знає специфіку проекту глянула

**Comment by ITsvetkoFF** [comment]
це недодивились розробники. посилання на сервак має братись з сервісу констант (тобто всюди має бути однакове)

**Comment by ITsvetkoFF** [comment]
тобто в сервісі копіювання таймперіодів треба лише брати значення з сервісу Констант.

**Comment by ITsvetkoFF** [comment]
fixed

**Comment by MPushkar** [comment]
Was tested on <a href="http://194.44.198.220/job/ums-admission-frontend/19/changes">Build #19 (Jun 25, 2015 7:19:53 AM)</a>.
