### ISSUE TITLE
[critical] Filters within same group on  "Персони" tab should work as 'and'

### ISSUE THREAD

**Issue by MPushkar** [ifnul/ums-admission-frontend#46]
Pre-conditions:
- Both male and female records should be present in a list of persons.

Steps to reproduce:
1. Login to system under Admin and go to a "Персони" tab.
2. Select "Стать чоловіча" option.
3. Select "Стать жіноча" option.
4. Click "Оновити" button.

Expected result:
Both male and female records should be present in the list of persons.

Actual result:
Only FEMALE records are shown in the list of persons.

It happens because the "Стать жіноча" option is the last one, which has been selected within the "Стать" group. As a result, the "Стать чоловіча" option was ignored.

The issue is reproducible on another filters as well (e.g. on a "Тип персони" field).

**Comment by ivanursul** [comment]
так виглядає, що це те саме, що Саша зауважив.Завтра буду дивитись до цього

**Comment by MPushkar** [comment]
Was tested on Build#29.
