### ISSUE TITLE
[critical] Чутливість до регістру

### ISSUE THREAD

**Issue by Krapka** [ifnul/ums-admission-frontend#47]
Прибрати чутливість до регістру в пошукових полях (на сторінках "персони" та "заяви")

**Comment by ivanursul** [comment]
Сів, подумав, думки вслух:
Мені здається доцільніше буде прибрати чутливість до регістру на стороні фронтенду - поясню чому: Якщо ми, приймаючи значення на бекенді - будемо їх перетворювати в lower case - ми таким чином обмежимо наше API до конкретного кейсу. Якщо в майбутньому нам потрібно буде шукати по критеріях чутливості - в нас такої можливості не буде.

Постараюсь завтра на фронтенді пофіксати цю ішшю.

**Comment by mkozhukharenko** [comment]
тобто на фронтенді потрібно перетворювати всі пошукові запити до lower case?

**Comment by ivanursul** [comment]
Та, здалось би
Візьмешся ?)
Якщо не хоч, завтра сам зроблю

**Comment by mkozhukharenko** [comment]
поки за персони-заяви взявся )

**Comment by ivanursul** [comment]
От сів собі ше думати, і розумію, що це не вийде на стороні фронтенду зробити.Дані ж в базі зберігаються по різному.
Не роби поки того
