### ISSUE TITLE
[low] "Заяви"->"Додавання заяви": "Шкала оцiнювання" drop-down list has no values

### ISSUE THREAD

**Issue by MPushkar** [ifnul/ums-admission-frontend#52]
Steps to reproduce:
1. Login to System under Admin and go to a "Заяви" tab.
2. Click "+ Додати заяву" button to open an input form.
3. Expand the "Шкала оцiнювання" drop-down list.

Expected result:
"Шкала оцiнювання" drop-down list should be expanded with pre-defined values.

Actual result:
"Шкала оцiнювання" drop-down list has no pre-defined values and user is not able to enter any value into this field manually.

**Comment by mkozhukharenko** [comment]
де можна отримати pre-defined values ?

**Comment by mkozhukharenko** [comment]
GET /marks/scales/types
GET /marks/scales
повертають путсі масиви

чи ці значення потрібно просто захардкодити?

**Comment by illay1994** [comment]
ні ці дані я додам зараз

**Comment by illay1994** [comment]
додав дані але вони не появилися у на frontEnd

**Comment by mkozhukharenko** [comment]
зараз поправлю фронтенд

**Comment by mkozhukharenko** [comment]
fixed, please test

**Comment by MPushkar** [comment]
<b>Ilya</b>,

Is the following list of options full?
Is the spelling correct?

<b>п"ятибальна
дванадцятибальна
шестидесятибальна
стобальна
двохсотбальна
ECTS
спiвбесiда</b>

**Comment by mkozhukharenko** [comment]
:heavy_exclamation_mark: marksale field need to be added in backend side

**Comment by mkozhukharenko** [comment]
:white_check_mark: works fine

**Comment by mkozhukharenko** [comment]
test please

**Comment by MPushkar** [comment]
<b>Kolya</b>,

Is the following list of options full?
Is the spelling correct?

<b>п"ятибальна
дванадцятибальна
шестидесятибальна
стобальна
двохсотбальна
ECTS
спiвбесiда</b>

**Comment by mkozhukharenko** [comment]
@illay1994 added this info to the data base, I got it from there. I think so

**Comment by illay1994** [comment]
Допустимі значення:
п'ятибальна
дванадцятибальна
шестидесятибальна
стобальна
двохсотбальна
ECTS
співбесіда

**Comment by MPushkar** [comment]
Was tested on Build#30.
