### ISSUE TITLE
[critical] Nothing happens after clicking "+ Додати новий документ" button

### ISSUE THREAD

**Issue by MPushkar** [ifnul/ums-admission-frontend#53]
Steps to reproduce:
1. Login to system under Admin and go to a "Заяви" tab.
2. Click "+ Додати заяву" button to open an input form.
3. Click "+ Додати новий документ" button to attach a new document.

Expected result:
A form for a new document should be opened.

Actual result:
Nothing happens after clicking the "+ Додати Додати новий документ" button.

**Comment by Krapka** [comment]
Документ додається якщо він створений в персоні

**Comment by mkozhukharenko** [comment]
Якщо персону не вибирати через пошук який є на сторінці "Додавання заяви" то документи персони (навіть якщо вони є і підходят paperUsage 2) не підтягуються. 

Тобто якщо зробии кроки
2. Click "+ Додати заяву" button to open an input form.
3. Click "+ Додати новий документ" button to attach a new document.

то в випадаючому списку пусто.

**Comment by mkozhukharenko** [comment]
:white_check_mark: fixed, please test

**Comment by MPushkar** [comment]
Was tested on Build#29.
