### ISSUE TITLE
[low] Move "I'мя (англ)" and "Прізвище (англ)" fields under the name fields in ukrainian

### ISSUE THREAD

**Issue by MPushkar** [ifnul/ums-admission-frontend#57]
Tabulation for current scheme is following:
![lnu_tabuation1](https://cloud.githubusercontent.com/assets/12950571/8310122/b87c12fa-19d6-11e5-9047-93bcc79508aa.png)

Such scheme is not very comfortable to use because user should switch the keyboard few times to type-in all values.

Offered scheme is following:
![lnu_tabuation2](https://cloud.githubusercontent.com/assets/12950571/8310231/3a1eec06-19d7-11e5-8f13-a7508cd6985b.png)
In this case user will first enter name in Ukrainian and only after that - in English.

Otherwise - we can change the tabulation for these fields.

**Comment by mkozhukharenko** [comment]
parent task #68

**Comment by mkozhukharenko** [comment]
fixed, test please

**Comment by MPushkar** [comment]
Was tested on Build#39.
