### ISSUE TITLE
[low] An input form doesn't fit the screen after resize

### ISSUE THREAD

**Issue by MPushkar** [ifnul/ums-admission-frontend#58]
Steps to reproduce:
1. Login to system under Admin and go to a "Пропозиції" tab.
2. Select any "Вступна кампанія" and resize the screen.

Actual result:
Screen is resized and all controls are shown within the input form.

Expected result:
Some controls and fields are beyond the input form.

![lnu_beyond_border](https://cloud.githubusercontent.com/assets/12950571/8328166/138b4b7a-1a77-11e5-8f75-9ca47eddd199.png)

Please note that this issue should be fixed for "Пропозиції", "Персони" and "Заяви" tabs.

**Comment by mkozhukharenko** [comment]
це баг закриється таскою #97
