### ISSUE TITLE
[low] Збивається дата ("додавання заяви")

### ISSUE THREAD

**Issue by Krapka** [ifnul/ums-admission-frontend#65]
В "додаванні заяви" всі дати відображаються некоректно. Збиваються після переходу на інші вкладки
![9ddaed8189c4779ba5c2b040926fba3b](https://cloud.githubusercontent.com/assets/8030424/8359035/8cfb863c-1b6c-11e5-96e9-e669af01bdeb.png)

**Comment by mkozhukharenko** [comment]
:white_check_mark: fixed
