### ISSUE TITLE
Change Request: Default number of records displayed per page should be 10 for "Персони" and "Заяви"

### ISSUE THREAD

**Issue by MPushkar** [ifnul/ums-admission-frontend#69]
<b>This issue is a Change Request from Ilya</b>

Pre-conditions:
- At least 11 records should be present on a "Персони" tab.

Steps to reproduce:
1.Log-in to System under Admin and go to the "Персони" tab.

Actual result:
All records are shown on the screen.
Marker "10" is not selected:
![lnu_records_per_page1](https://cloud.githubusercontent.com/assets/12950571/8377451/121475f6-1c1a-11e5-8a5f-7ae6e52381fe.png)

Expected result:
Records are shown as 10 per page.
User is able to turn the pages and each time next 10 records are shown.
Marker "10" is selected by default:
![lnu_records_per_page2](https://cloud.githubusercontent.com/assets/12950571/8377485/6669c03e-1c1a-11e5-92cd-90e37d0cce45.png)

**Comment by MPushkar** [comment]
<b>Returned.</b>

Pre-conditions:
At least 11 records should be present on a "Персони" tab.

Steps to reproduce:
1. Log-in to System under Admin and go to the "Персони" tab.
[remember the records that are shown in grid on page 1]
2. Go to page 2.

Actual result:
Same records are shown on the page 2.

Expected result:
User should be able to turn the pages and each time <b>next</b> 10 records should be shown.

**Comment by MPushkar** [comment]
<b>Update.</b>
User should be able to select sorting order and turn the pages according to this order.

Actual result:
Ordering of records <b>resets to default</b> each time after turning the pages.

**Comment by MPushkar** [comment]
<b>Returned.</b>
1) Switching from "10" records to "100" records <b>doesn't work</b>.
2) The default number of records for "Заяви" <b>is not 10</b>.

**Comment by MPushkar** [comment]
<b>Returned.</b>
The default number of records for "Заяви" is not 10.

**Comment by illay1994** [comment]
fixed, please test

**Comment by MPushkar** [comment]
Was tested on Build#40.
