### ISSUE TITLE
Following tabs should be hidden from Frontend: "Пропозиції" and "Статистика" (valid for version 1.0)

### ISSUE THREAD

**Issue by MPushkar** [ifnul/ums-admission-frontend#70]
<b>Change Request from Ilya</b>

Following tabs should be hidden from Frontend:
- "Пропозиції";
- "Статистика".

This change request is temporary and <b>valid for version 1.0 only</b>.

**Comment by mkozhukharenko** [comment]
is this task actual? If no - please close it

**Comment by MPushkar** [comment]
Kolya, current task <b>is required</b> because user <b>shouldn't be able</b> to use "Пропозиції" and "Статистика" functionalities on version 1.0.

**Comment by mkozhukharenko** [comment]
Ok
Is this means that temporary all issues about "Пропозиції" and "Статистика" is no actual?

**Comment by MPushkar** [comment]
Yes, so far.
I've changed the priority to "Low".

**Comment by mkozhukharenko** [comment]
make menu items "Пропозиції" and "Статистика" hidden in the header
but they are still available through url:
"Пропозиції" - _#/specoffer/list_
"Статистика" - _#/statistics_

**Comment by MPushkar** [comment]
<b>Testing is Blocked</b> until the functionality is deployed on Master env.

**Comment by mkozhukharenko** [comment]
![](http://i.imgur.com/80dckw1.png)

**Comment by MPushkar** [comment]
Was tested on Build#39.
Labels "Пропозиції" and "Статистика" are not hidden but are disabled on the Frontend. This fix is acceptable.
