### ISSUE TITLE
Баг при відображенні списку персон

### ISSUE THREAD

**Issue by ITsvetkoFF** [ifnul/ums-admission-frontend#8]
при відкритті персон далі натискаєм щоб посортувати по id виникає таке
можливо значення по замовченні в якісь змінні стоїть 1

**Comment by ITsvetkoFF** [comment]
https://cloud.githubusercontent.com/assets/10198202/7670280/f45935d4-fca6-11e4-877d-09dc28251fbb.png

**Comment by okrasn** [comment]
Не зміг репродюснути

**Comment by MPushkar** [comment]
Closed as <b>Not reproducible</b>.
