### ISSUE TITLE
Гортання сторінок в "Пропозиції"

### ISSUE THREAD

**Issue by Krapka** [ifnul/ums-admission-frontend#84]
Некоректно працює пагінація - кнопки "«" та "»" рухаються лише на одну сторінку (вперед або назад), а мали б повертати в початок або кінець списку відповідно. 
Ну і потрібно додати можливість переходити в кінець/початок списку.

Пропоную встановити таку ж форму, як в персонах
![4f3b4ce8b48f330986b09be3019999d9](https://cloud.githubusercontent.com/assets/8030424/8476792/6254a3f8-20cd-11e5-94ca-8e946a24d06a.png)

**Comment by mkozhukharenko** [comment]
це баг закриється  таскою #97
