### ISSUE TITLE
User is not able to save  "Заява". Nothing happens after ckicking "Зберегти" button.

### ISSUE THREAD

**Issue by MPushkar** [ifnul/ums-admission-frontend#85]
Nothing happens after clicking "Зберегти" button.
Following error is shown in Web Console when user tries to save newly created "Заява":

16:36:15.521 "Error: currentObj is undefined
addOrEditEnrolment@http://194.44.198.221/scripts/services/enrolments/EnrolmentREST.js:88:9
$scope.sendToServer@http://194.44.198.221/scripts/controllers/enrolments/newEnrolment.js:66:9
$parseFunctionCall@http://194.44.198.221/bower_components/angular/angular.js:12448:15
ngEventHandler/</callback@http://194.44.198.221/bower_components/angular/angular.js:21673:17
$RootScopeProvider/this.$get</Scope.prototype.$eval@http://194.44.198.221/bower_components/angular/angular.js:14547:16
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://194.44.198.221/bower_components/angular/angular.js:14646:18
ngEventHandler/<@http://194.44.198.221/bower_components/angular/angular.js:21678:17
jQuery.event.dispatch@http://194.44.198.221/bower_components/jquery/dist/jquery.js:4434:15
jQuery.event.add/elemData.handle@http://194.44.198.221/bower_components/jquery/dist/jquery.js:4121:6
"1 angular.js:11699:17
consoleLog/<() angular.js:11699
$ExceptionHandlerProvider/this.$get</<() angular.js:8628
$RootScopeProvider/this.$get</Scope.prototype.$apply() angular.js:14648
ngEventHandler/<() angular.js:21678
jQuery.event.dispatch() jquery.js:4434
jQuery.event.add/elemData.handle() jquery.js:4121

**Comment by mkozhukharenko** [comment]
незрозуміло як має виглядати POST запит до серверу

headers
`
"Authorization Basic": "YWRtaW46bmltZGE="
"Content-Type": "application/json"
`
body

```
{
  "personId": 9,
  "parentId": 0,
  "specOfferId": 134,
  "departmentId": 242,
  "personPaperId": 0,
  "enrolmentTypeId": 0,
  "begDate": "2015-07-04",
  "endDate": "2015-07-04",
  "isContract": 0,
  "mark": 0,
  "isState": 0,
  "docSeries": "DF",
  "docNum": "12",
  "docText": "",
  "isPrivilege": 0,
  "isHostel": 0,
  "isEducationState": 0,
  "isInterview": 0,
  "isOriginal": 0,
  "evDate": "2015-07-04",
  "priority": 0,
  "createDate": "2015-07-04",
  "updateDate": "2015-07-04",
  "note": "",
  "id": 0,
  "utid": "",
  "crtUser": "",
  "crtUserGroup": "",
  "uapp": "",
  "uid": 0,
}
```

повертає помилку 404

що означають поля utid, crtUser, crtUserGrou, uapp, uid ?
uri не потрібен

**Comment by mkozhukharenko** [comment]
Потрібно на сервері додати поле markscaletype (шкала оцінювання) #52

**Comment by mkozhukharenko** [comment]
(!) "endDate" is required. 
need to be chacked

**Comment by mkozhukharenko** [comment]
fixed, please test

**Comment by MPushkar** [comment]
Was tested on Build#29.
