### ISSUE TITLE
User input validation - new Enrolment form

### ISSUE THREAD

**Issue by mkozhukharenko** [ifnul/ums-admission-frontend#91]
Реалізувати валідацію на стороні фронтенда у формі "новая заява"
Серія заяви - (латиниця_кирилиця_цифри) ?
Номер заяви - лише цифри, максимальна довижна ?
Загальний бал - цифри, максимальна величина ?
Пріоритет - мінімум 1, максимум 15

**Comment by illay1994** [comment]
Номер лише цифри

**Comment by illay1994** [comment]
Серія чифри тільки кирилиця  або тільки латинь

**Comment by mkozhukharenko** [comment]
:white_check_mark: added
